### ISSUE TITLE
Magento 2.2.4 breaks compilation

### ISSUE THREAD

**Issue by Kroellie** [swissup/email#6]
Repositories code generation... 1/7 [====>-----------------------]  14% < 1 sec 52.0 MiBPHP Fatal error:  Class Swissup\Email\Model\Transport\Smtp contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (Magento\Framework\Mail\TransportInterface::getMessage) in /var/www/webshop/vendor/swissup/email/Model/Transport/Smtp.php on line 9

**Comment by 0m3r** [comment]
It was  fixed  on 22 Aug 2017 https://github.com/swissup/email/commit/00298d921053e0da4bf3c2200ce89b5d5f76affc#diff-303ecaf874ab4bb96c43c9824ff7b520

https://github.com/swissup/email/blob/master/Model/Transport/Smtp.php#L77

Just update your swissup/email
~~~
composer update  swissup/email
~~~
